### PR TITLE
Configuring for pure-python

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Comment by icemac** [comment]
Drop in coverage is because of the switch to branch coverage.

**Comment by gforcada** [comment]
With all the changes since then, it might be worth re-running `zopefoundation/meta` again? 🤔

**Comment by icemac** [comment]
Wow, I actually forgot about this PR.

**Comment by icemac** [comment]
Adapted to new state of `meta/config`.

**Review by gforcada — APPROVED** [review]

**Pull request merged**
